apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIk9UUXlNVFUxTkRVNlVFQnpjM2N3Y21RaFFDTWtKUT09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
