apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: notepad
    type: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
