apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: notepad
    type: database
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: notepad
    type: database
 
